name: Nes workflow

on:
    - push
    - pull_request

jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
      matrix:
            node-version: [14.x]

      steps:
              - uses: actions/checkout@v2
              - name: Use Node.js ${{ matrix.node-version }}
              - uses: actions/setup-node@v2
                with: 
                  node-version: ${{ matrix.node-version }}
             - name: npm install
                  run: make install-deps
                  env:
                    CI: true
              - name: Run linter
                run: |
                  make lint
